
- name: provision tower ec2 instances
  ec2_instance:
      key_name: "{{ ssh_key_name }}"
      group: "{{ sec_group.group_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: true
      exact_count: 3
      count_tag: tower
      region: "{{ region }}"
      instance_tags:
        Name: tower
        role: tower
  register: ec2

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=ec2hosts
  loop: "{{ ec2.instances }}"