
- name: provision tower ec2 instances
  ec2_instance:
      key_name: "{{ ssh_key_name }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
      wait: true
      region: "{{ region }}"
      tags:
        role: tower
      name: tower
  register: tower