---
- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: deploy ec2 instances
      include_role:
        name: common
      when: state == "present"

- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: terminate ec2 instances
      include_role:
        name: cleanup
      when: state == "absent"
