---
- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: deploy ec2 instances
      include_role:
        name: tower
      when: cleanup == "false"

- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: terminate ec2 instances
      include_role:
        name: cleanup
      when: cleanup == "true"
