---
- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: deploy tower ec2 instances
      import_role:
        name: tower
      when: state == "present"
    - name: deploy automate ec2 instances
      import_role:
        name: automate
      when: state == "present"

- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: terminate ec2 instances
      include_role:
        name: cleanup
      when: state == "absent"
